[platformio]
default_envs = esp32-c3-supermini
src_dir = src

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
monitor_speed = 115200
framework = espidf
monitor_filters = esp32_exception_decoder
board_upload.flash_size = 2MB
